add thread control for pytorch backend
triton-inference-server/pytorch_backend pull request #125
Opened 2024-03-06 07:04 UTC by yongbinfeng

As noted in the issue here: https://github.com/triton-inference-server/server/issues/6896 we have found out the number of threads can affect the pytorch inference performance a lot. In some cases we have seen PyTorch inference runs (super) slow on multi-core CPU machines, and just setting number of instance is not enough to handle the problem. We have tested using `at::set_num_threads(1)` and confirmed this fixes the slow inference issue.

This PR allows to configure `intra_op_thread_count` and `inter_op_thread_count` for pytorch models, similar to other backends such as TF and ONNX, with syntax such as

```
parameters { key: "INTRA_OP_THREAD_COUNT" value: { string_value: "1" } }
parameters { key: "INTER_OP_THREAD_COUNT" value: { string_value: "1" } }
```

2024-03-13 17:11 UTC, pascualex commented
Thank you for this, we are experiencing the same problem and are being forced to convert our models to ONNX, which in turn is causing other issues.

I'm not a maintainer so I can only validate that this is a real issue for us too.

2024-04-18 19:51 UTC, tanmayv25 requested changes

2024-04-18 19:51 UTC, tanmayv25 commented on src/libtorch.cc
> +    err = ParseParameterInt(
```suggestion
    err = ParseParameter(
```

2024-04-18 19:51 UTC, tanmayv25 commented on src/libtorch_utils.cc
> +ParseParameterInt(
```suggestion
ParseParameter(
```

2024-04-18 19:51 UTC, tanmayv25 commented on src/libtorch_utils.h
> +TRITONSERVER_Error* ParseParameterInt(
```suggestion
TRITONSERVER_Error* ParseParameter(
```

2024-04-18 19:51 UTC, tanmayv25 commented on src/libtorch.cc
> +    err = ParseParameterInt(
```suggestion
    err = ParseParameter(
```

2024-04-18 19:51 UTC, tanmayv25 commented on src/libtorch.cc
We can use function overloading on ParseParameter.
Additionally, can you update the copyright years? 2023 -> 2024?

2024-04-18 19:51 UTC, tanmayv25 commented on src/libtorch_utils.cc
Update the copyright years.

2024-04-18 19:51 UTC, tanmayv25 commented on src/libtorch_utils.h
Update the copyright years.

2024-04-18 19:52 UTC, yongbinfeng commented
> Triton CLA

I think I've done already that, through my affiliation (fermilab) and my affiliation email. (The other PR is already merged: https://github.com/triton-inference-server/pytorch_backend/pull/120 so hopefully it should be fine I guess?)

2024-04-18 21:29 UTC, tanmayv25 approved these changes

2024-04-18 21:30 UTC, merged

2024-04-18 21:30 UTC, tanmayv25 commented
Thanks for your contribution!