Add CUDA cache cleaning flag to pytorch backend
triton-inference-server/pytorch_backend pull request #61
Opened 2022-04-30 13:50 UTC by zeruniverse

Implemented a flag similar to `memory_arena_shrinkage` in ONNXRuntime backend. With `ENABLE_CACHE_CLEANING` set to `true`, CUDA cache gets cleared after each model execution. This will enable us to serve more models in one GPU.

2022-06-30 20:33 UTC, manhtd98 commented
why we not merge it? i have the same problem

2022-06-30 21:25 UTC, tanmayv25 commented
This might have fell through the cracks. Thanks for bringing it up.

2022-06-30 21:34 UTC, tanmayv25 requested changes

2022-06-30 21:34 UTC, tanmayv25 commented on src/libtorch.cc
> +  // Clear cache
Clear CUDA cache

2022-06-30 21:34 UTC, tanmayv25 commented on src/libtorch.cc
> +  if(model_state->EnabledCacheCleaning()) instance_state->ClearCache();
enclose the call  within braces.

2022-06-30 21:36 UTC, tanmayv25 commented on README.md
> +If not specified, cache cleaning is disabled. This flag has no effect if model is on CPU.
You should also talk about how it would penalize the performance.

2022-07-01 02:52 UTC, zeruniverse commented
@tanmayv25 do you have a CLA version for individual contributor? This CLA is for corporation.

2022-07-01 23:07 UTC, tanmayv25 commented
@zeruniverse  Just provide your name instance of company name in the form. We use the same form for company and individual.

2022-07-04 11:17 UTC, zeruniverse commented
@tanmayv25 

- [x] CLA sent to triton-cla at nvidia dot com

- [x] addressed review comments

- [ ] perf data (do we need it? I have no hardware to do a thorough perf test)

2022-07-05 18:54 UTC, tanmayv25 commented
Thanks @zeruniverse! I will add some sanity testing for this on our CI and merge the changes.

2022-07-05 18:56 UTC, tanmayv25 approved these changes

2022-07-06 00:01 UTC, merged