Update pytorch docker image tag to 22.12 in README.md
triton-inference-server/pytorch_backend pull request #91
Opened 2023-01-31 04:09 UTC by yeahdongcn

nvcr.io/nvidia/pytorch:21.02-py3 doesn't contain /usr/local/lib/python3.8/dist-packages/torch/lib/*, following the build instructions in README.md will fail with errors.

2023-02-02 00:23 UTC, dyastremsky commented
Thank you for contributing this pull request! Can you please send in a [Contributor License Agreement (CLA)](https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) if you haven't yet?

2023-02-02 01:38 UTC, yeahdongcn commented
> Thank you for contributing this pull request! Can you please send in a [Contributor License Agreement (CLA)](https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) if you haven't yet?

Done.

2023-02-02 18:08 UTC, dyastremsky commented
Thank you. We'll review this shortly.

2023-02-09 20:38 UTC, dyastremsky requested changes
We've received your CLA and this works on our end as well. Thank you for your contribution! Would you be able to update line 2: the copyright should now read "2020-2023" due to this update. That's just required to keep everything current to merge this PR. Thank you again!

2023-02-10 00:42 UTC, yeahdongcn commented
> We've received your CLA and this works on our end as well. Thank you for your contribution! Would you be able to update line 2: the copyright should now read "2020-2023" due to this update. That's just required to keep everything current to merge this PR. Thank you again!

No problem. Please see the new commit. Thanks.

2023-02-10 01:16 UTC, dyastremsky approved these changes
Wonderful, great work! Merging.

2023-02-10 01:21 UTC, merged